#ifndef STRING_CONSTANTS
#define STRING_CONSTANTS



#define STR_MENU_NAME "[Set](Name):"
#define STR_MENU_DESCRIPTION "[Set/Edit](Desc):"
#define STR_MENU_OBJECT "[Create/Delete/Edit](Object):"
#define STR_MENU_CREATURE "[Create/Delete/Edit](Creature):"
#define STR_MENU_EXIT "[Create/Delete/Edit](Exit):"
#define STR_MENU_USE_ALIAS "[Add/Remove](UseAlias):"
#define STR_MENU_HITPOINTS "[Set](Hitpoints):"
#define STR_MENU_ROOM "[Set/Edit/New](Room):"
#define STR_MENU_DAMAGE "[Set](Damage):"
#define STR_MENU_TAKEABLE "[Set](Takeable)[T/F]:"
#define STR_MENU_CAN_OPEN "[Set](Openable)[T/F]:"
#define STR_MENU_IS_OPEN "[Set](Open)[T/F]:"

#define STR_EXIT "exit"
#define STR_SET "set"
#define STR_EDIT "edit"
#define STR_CREATE "create"
#define STR_OBJECT "object"
#define STR_CREATURE "creature"
#define STR_DESCRIPTION "description"
#define STR_DESC "desc"
#define STR_NAME "name"
#define STR_USE_ALIAS "usealias"
#define STR_ADD "add"
#define STR_ENTER "enter"
#define STR_SAVE "save"
#define STR_LOAD "load"
#define STR_HITPOINTS "hitpoints"
#define STR_ROOM "room"
#define STR_USE "use"
#define STR_DAMAGE "damage"
#define STR_TRUE "Yes"
#define STR_FALSE "No"
#define STR_TAKEABLE "takeable"
#define STR_OPENABLE "openable"
#define STR_TAKE "take"
#define STR_LOOK "look"
#define STR_OPEN "open"
#define STR_PUT "put"
#define STR_PLACE "place"


#define STR_TAB  "    "
#define STR_ARROW "->"
#define STR_JOINER ","
#define STR_PROMPT ">"
#define STR_ELLIPSES "..."
#endif
